apiVersion: 1
datasources:
  - name: TradeLog
    type: frser-sqlite-datasource
    uid: tradelog-sqlite
    access: proxy
    jsonData:
      path: /app/data/trade_log.db
    isDefault: true
    editable: false

  - name: SwarmDB
    type: frser-sqlite-datasource
    uid: swarm-sqlite
    access: proxy
    jsonData:
      path: /swarm/data/swarm.db
    isDefault: false
    editable: false
