#!/usr/bin/env python3
"""Runtime control-plane writer for poly1.

This is the single command surface for changing trading mode. It writes:

- deploy/.env.runtime: Docker env overrides, no secrets.
- data/runtime_control.json: volume-shared control file read by RiskGate.
- data/HALT: physical brake in freeze mode.
"""

from __future__ import annotations

import argparse
import hashlib
import json
from datetime import datetime, timezone
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
POLICY_PATH = ROOT / "deploy/runtime_policy.json"
ENV_RUNTIME_PATH = ROOT / "deploy/.env.runtime"
CONTROL_PATH = ROOT / "data/runtime_control.json"
HALT_PATH = ROOT / "data/HALT"


BASE_ENV = {
    "RUNTIME_CONTROL_PATH": "/app/data/runtime_control.json",
    "ALLOC_SYNC_ENFORCE": "false",
    "ALLOCATOR_EXPLORATION_USDC": "0",
    "WALLET_SCOUT_ENABLE": "false",
    "SWARM_RESERVE_USDC": "0",
    "SCALPER_RESERVE_USDC": "0",
    "BTC_DAILY_RESERVE_USDC": "0",
    "NEAR_RESOLUTION_RESERVE_USDC": "0",
    "NEWS_SHOCK_RESERVE_USDC": "0",
    "WALLET_FOLLOW_RESERVE_USDC": "0",
    "EXECUTE": "false",
    "EXECUTE_SCALPER": "false",
    "EXECUTE_BTC_DAILY": "false",
    "EXECUTE_NEAR_RESOLUTION": "false",
    "EXECUTE_NEWS_SHOCK": "false",
    "EXECUTE_WALLET_FOLLOW": "false",
    "EXECUTE_MAINTAIN": "true",
    "TRADING_SUPERVISOR_ENFORCE_HALT": "true",
    "TRADING_SUPERVISOR_EVAL_GRACE_SEC": "180",
    "TRADING_SUPERVISOR_STALE_HEARTBEAT_SEC": "180",
}


def _utc_now() -> str:
    return datetime.now(timezone.utc).isoformat()


def _load_policy() -> dict:
    return json.loads(POLICY_PATH.read_text())


def _hash_payload(payload: dict) -> str:
    raw = json.dumps(payload, sort_keys=True, separators=(",", ":")).encode()
    return hashlib.sha256(raw).hexdigest()[:16]


def _write_env(env: dict[str, str]) -> None:
    lines = [
        "# Generated by scripts/runtime_control.py. No secrets here.",
        "# Do not edit by hand; use runtime_control.py freeze/live-probe.",
        "",
    ]
    for key in sorted(env):
        lines.append(f'{key}="{env[key]}"')
    ENV_RUNTIME_PATH.write_text("\n".join(lines) + "\n")


def _write_control(control: dict) -> None:
    CONTROL_PATH.parent.mkdir(parents=True, exist_ok=True)
    CONTROL_PATH.write_text(json.dumps(control, indent=2, sort_keys=True) + "\n")


def _set_halt(message: str) -> None:
    HALT_PATH.parent.mkdir(parents=True, exist_ok=True)
    HALT_PATH.write_text(message.rstrip() + "\n")


def freeze(args: argparse.Namespace) -> int:
    env = dict(BASE_ENV)
    control_base = {
        "mode": "freeze",
        "allowed_live_agents": [],
        "requires_halt": True,
    }
    config_hash = _hash_payload({"env": env, "control": control_base})
    env["RUNTIME_MODE"] = "freeze"
    env["RUNTIME_CONFIG_HASH"] = config_hash
    control = {
        **control_base,
        "config_hash": config_hash,
        "updated_at": _utc_now(),
        "updated_by": "scripts/runtime_control.py freeze",
        "note": args.note or "stability freeze; live entries disabled",
    }
    _write_env(env)
    _write_control(control)
    _set_halt(
        "HALT set by runtime_control.py freeze: no live entry agents until "
        "runtime_control.py live-probe and preflight --mode live pass."
    )
    print(f"runtime mode set: freeze hash={config_hash}")
    print(f"wrote {ENV_RUNTIME_PATH}")
    print(f"wrote {CONTROL_PATH}")
    print(f"wrote {HALT_PATH}")
    return 0


def live_probe(args: argparse.Namespace) -> int:
    policy = _load_policy()
    agents = policy["entry_agents"]
    if args.agent not in agents:
        valid = ", ".join(sorted(agents))
        raise SystemExit(f"unknown agent {args.agent!r}; valid: {valid}")

    budget = float(args.budget)
    if budget <= 0:
        raise SystemExit("--budget must be positive")

    env = dict(BASE_ENV)
    env["RUNTIME_MODE"] = "live_probe"
    env["EXECUTE"] = "true"
    spec = agents[args.agent]
    env[spec["execute_flag"]] = "true"
    if spec.get("reserve_flag"):
        env[spec["reserve_flag"]] = str(budget)

    control_base = {
        "mode": "live_probe",
        "allowed_live_agents": [args.agent],
        "budget_usdc": budget,
        "requires_halt": False,
    }
    config_hash = _hash_payload({"env": env, "control": control_base})
    env["RUNTIME_CONFIG_HASH"] = config_hash
    control = {
        **control_base,
        "config_hash": config_hash,
        "updated_at": _utc_now(),
        "updated_by": "scripts/runtime_control.py live-probe",
        "note": args.note or f"live probe for {args.agent}",
    }
    _write_env(env)
    _write_control(control)
    if args.arm:
        HALT_PATH.unlink(missing_ok=True)
    print(f"runtime mode set: live_probe agent={args.agent} budget={budget} hash={config_hash}")
    print(f"wrote {ENV_RUNTIME_PATH}")
    print(f"wrote {CONTROL_PATH}")
    if args.arm:
        print(f"removed {HALT_PATH}")
    else:
        print(f"left {HALT_PATH} unchanged; pass --arm only after approval")
    return 0


def status(_: argparse.Namespace) -> int:
    print(f"env_runtime_exists={ENV_RUNTIME_PATH.exists()} path={ENV_RUNTIME_PATH}")
    print(f"control_exists={CONTROL_PATH.exists()} path={CONTROL_PATH}")
    print(f"halt_exists={HALT_PATH.exists()} path={HALT_PATH}")
    if CONTROL_PATH.exists():
        print(CONTROL_PATH.read_text().rstrip())
    return 0


def main() -> int:
    parser = argparse.ArgumentParser()
    sub = parser.add_subparsers(dest="cmd", required=True)

    p_freeze = sub.add_parser("freeze")
    p_freeze.add_argument("--note", default="")
    p_freeze.set_defaults(func=freeze)

    p_live = sub.add_parser("live-probe")
    p_live.add_argument("--agent", required=True)
    p_live.add_argument("--budget", type=float, default=5.0)
    p_live.add_argument("--note", default="")
    p_live.add_argument("--arm", action="store_true", help="remove HALT after writing live control")
    p_live.set_defaults(func=live_probe)

    p_status = sub.add_parser("status")
    p_status.set_defaults(func=status)

    args = parser.parse_args()
    return args.func(args)


if __name__ == "__main__":
    raise SystemExit(main())
